### ISSUE TITLE
inconsistent docker-compose files

### ISSUE THREAD

**Issue by tstorek** [Fiware/tutorials.Step-by-Step#8]
Hello,

thanks for the brilliant tutorials. It seems as if the docker-compose files have inconsistencies within the names of services and hostname from one section to the other (e.g. mongodb and mongo-db). It would be great if the tutorial would also allaborate the influence of containernames and hostnames on the configuration of context-providers because from my experience this can be confusing.

To the best of my knowledge "container_name" and "expose" are no longer allowed. Also extra healthchecks are not allowed when using docker stack.

Thanks,

Thomas

**Comment by jason-fox** [comment]
Hi Thomas,

Could you elaborate? As far as I can see the ownly misaligned files are within the QuantumLeap Tutorial. Are there others you have found?  Also the IoT Agents have an `ENV` called `mongodb` when it is not using memory persistence, but that can't be changed.

The yaml files (hopefully) consistently set `container_name` and `hostname` to avoid reliance on the implicit naming of the service itself. They make the naming explicit.

Regarding `container_names`, databases are prefixed `db`, FIWARE components are prefixed `fiware`

If this needs to be elaborated, I guess the obvious location is somewhere in  https://github.com/FIWARE/tutorials.Step-by-Step/blob/master/docs/index.md or maybe an additonal appendix after the lengthy cUrl commands. It  shouldn't really be in the main flow of the text since it is describing Docker not FIWARE, but maybe a link to another when each yaml is described would help.




## Docs README

 ```diff
-cratedb:
+crate-db:
     image: crate:2.3
-    hostname: cratedb
+    hostname: crate-db
     ports:
         - "4200:4200"
         - "4300:4300"
@@ -221,7 +221,7 @@ quantumleap:
     depends_on:
         - cratedb
     environment:
-        - CRATE_HOST=cratedb
+        - CRATE_HOST=crate-db
 ```

## QL README

 ```diff
-cratedb:
+crate-db:
     image: crate:2.3
-    hostname: cratedb
+    hostname: crate-db
     ports:
         - "4200:4200"
         - "4300:4300"
@@ -267,9 +267,9 @@ quantumleap:
     ports:
         - "8668:8668"
     depends_on:
-        - cratedb
+        - crate-db
     environment:
-        - CRATE_HOST=cratedb
+        - CRATE_HOST=crate-db
 ```
 

## QL docker-compose.yml

```diff
 version: "3.5"
 services:
-  mongodb:
+  mongo-db:
     image: mongo:3.6
-    hostname: mongodb
+    hostname: mongo-db
     container_name: db-mongo
     ports:
       - "27017:27017"
@@ -10,11 +10,11 @@ services:
       - default
     command: --bind_ip_all --smallfiles
     volumes:
-      - mongodb:/data
+      - mongo-db:/data
 
-  cratedb:
+  crate-db:
     image: crate:2.3
-    hostname: cratedb
+    hostname: crate-db
     container_name: db-crate
     ports:
       # Admin UI
@@ -23,13 +23,13 @@ services:
       - "4300:4300"
     command: -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
     volumes:
-      - cratedb:/data
+      - crate-db:/data
 
   grafana:
     image: grafana/grafana
     container_name: grafana
     depends_on:
-      - cratedb
+      - crate-db
     ports:
       - "3003:3000"
     environment:
@@ -60,9 +60,9 @@ services:
     ports:
       - "8668:8668"
     depends_on:
-      - cratedb
+      - crate-db
     environment:
-      - CRATE_HOST=cratedb
+      - CRATE_HOST=crate-db
     healthcheck:
       test: curl --fail -s http://localhost:8668/v2/version || exit 1
 
@@ -86,7 +86,7 @@ services:
       - IOTA_TIMESTAMP=true # Supply timestamp information with each measurement
       - IOTA_CB_NGSI_VERSION=v2 # use NGSIv2 when sending updates for active attributes
       - IOTA_AUTOCAST=true # Ensure Ultralight number values are read as numbers not strings
-      - IOTA_MONGO_HOST=mongodb # The host name of MongoDB
+      - IOTA_MONGO_HOST=mongo-db # The host name of MongoDB
       - IOTA_MONGO_PORT=27017 # The port mongoDB is listening on
       - IOTA_MONGO_DB=iotagentul # The name of the database used in mongoDB
       - IOTA_HTTP_PORT=7896 # The port used for device traffic over HTTP
@@ -137,6 +137,6 @@ networks:
         - subnet: 172.18.1.0/24
 
 volumes:
-  mongodb: ~
-  cratedb: ~
+  mongo-db: ~
+  crate-db: ~
   grafana: ~
```

**Comment by tstorek** [comment]
To the best of my knowledge "container_name" and "expose" are no longer allowed. Also extra healthchecks are not allowed when using docker stack. 

Those were at least the files I checked. For me it is not really clear if the service_name is used for mapping or the set hostname. If you change it the way you proposed it might be even more confusing ;)

What about a comment next to those arguments only to clarify their meaning for the configuration.

**Comment by jason-fox** [comment]
Which compose version are you referring to? Docker compose `3.7` still includes `container_name` and `expose` and `healthcheck`

-  https://docs.docker.com/compose/compose-file/#container_name
-  https://docs.docker.com/compose/compose-file/#expose
- https://docs.docker.com/compose/compose-file/#healthcheck

I'm not sure if the **Docker Stack** argument is relevant for the tutorials. The tutorials use `docker-compose` since its purpose is "for defining and running multi-container Docker applications" on a **single docker engine**.  The purpose within each tutorial is to keep the config as simple as possible so the student can concentrate on learning the FIWARE part.

The tutorial `docker-compose` files _as written_ are not for deployment, they just lump everything onto one machine. They contain various obvious security flaws - passwords in plain text, no load balancing, no use of HTTPS and so on. This it to avoid the need of multiple machines, generating certificates, encrypting secrets and so on, purely so that a single `docker-compose` file can be read as an example to build on, not use directly. A proper architecture has been sacrificed to keep the narrative focused on the learning goals.
 
So far the Tutorials are covering Core Context, IoT Agents and Security only. There is nothing on deployment and scaling yet. You would be much better looking at the [SmartSDK Recipes](https://smartsdk.github.io/smartsdk-recipes/).

I guess there is a growing need for a bibliography directing users elsewhere when the need arises, to cover more advanced concepts.

**Comment by tstorek** [comment]
Thanks. For the healthcheck I just know what docker-stack tells me when deploying. Same for expose, since docker does expose ports anyway when they are mapped. From the documentation I know saw that container_name is  simply ignored by docker stack. My appologizes ;) 
But you are right that this would probably go beyond the scope of the tutorial. I like it anyway:)

I also like the recipes you suggest. Do you know if they will evolve any further in future?

I think we can close this issue then, right?
